# Generated by Django 3.1.6 on 2021-02-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20210223_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcuser',
            name='useremail',
        ),
    ]
